/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolicitarRouteImport } from './routes/solicitar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebhooksPaymentsRouteImport } from './routes/api/webhooks/payments'

const SolicitarRoute = SolicitarRouteImport.update({
  id: '/solicitar',
  path: '/solicitar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaymentsRoute = ApiWebhooksPaymentsRouteImport.update({
  id: '/api/webhooks/payments',
  path: '/api/webhooks/payments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/solicitar': typeof SolicitarRoute
  '/api/webhooks/payments': typeof ApiWebhooksPaymentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/solicitar': typeof SolicitarRoute
  '/api/webhooks/payments': typeof ApiWebhooksPaymentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/solicitar': typeof SolicitarRoute
  '/api/webhooks/payments': typeof ApiWebhooksPaymentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/solicitar' | '/api/webhooks/payments'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/solicitar' | '/api/webhooks/payments'
  id: '__root__' | '/' | '/solicitar' | '/api/webhooks/payments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SolicitarRoute: typeof SolicitarRoute
  ApiWebhooksPaymentsRoute: typeof ApiWebhooksPaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitar': {
      id: '/solicitar'
      path: '/solicitar'
      fullPath: '/solicitar'
      preLoaderRoute: typeof SolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/payments': {
      id: '/api/webhooks/payments'
      path: '/api/webhooks/payments'
      fullPath: '/api/webhooks/payments'
      preLoaderRoute: typeof ApiWebhooksPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SolicitarRoute: SolicitarRoute,
  ApiWebhooksPaymentsRoute: ApiWebhooksPaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
